import "../styles/globals.css";

export const metadata = {
  title: "Popliving",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="fr">
      <body      >
        {children}
      </body>
    </html>
  );
}
